import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { hot } from "react-hot-loader/root";
import { setConfig } from "react-hot-loader";
import { Provider } from "react-redux";
import { ThemeProvider } from "@material-ui/core";

import { store } from "../src/store";
import { theme } from "../src/static/theme";
import { PersistGate } from "redux-persist/integration/react";
import { persistStore } from "redux-persist";
import Notifier from "@containers/Notifier/Notifier";
import GlobalLoader from "@containers/GlobalLoader/GlobalLoader";
import Snackbar from "@components/Snackbar/Snackbar";

setConfig({
  reloadHooks: false,
});

const Home: NextPage = () => {
  const persistor = persistStore(store);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <PersistGate loading={null} persistor={persistor}>
          <ThemeProvider theme={theme}>
            <Snackbar maxSnack={99}>
              <Notifier />
              <GlobalLoader />
            </Snackbar>
          </ThemeProvider>
        </PersistGate>
      </Provider>
    </div>
  );
};

// export default Home;
export default process.env.NODE_ENV === "development" ? hot(Home) : Home;
